FileTypes:
  - file_type: Word
    file_extension: docx
    mime: application/docx
  - file_type: Scalable Vector Graphic
    file_extension: svg
    mime: image/svg+xml
  - file_type: JPEG Image
    file_extension: jpeg
    mime: image/jpeg
  - file_type: PDF
    file_extension: pdf
    mime: application/pdf
  - file_type: Old Word
    file_extension: doc
    mime: application/doc
  - file_type: Comma Separated Value
    file_extension: csv
    mime: text/csv
  - file_type: Markdown
    file_extension: md
    mime: text/markdown
  - file_type: PNG Image
    file_extension: png
    mime: image/png
