functionalAreas:
  directory:
    enabled: true
    capability:
      index: DIRECTORY
  camps:
    enabled: false
  tasks:
    enabled: false
  documents:
    enabled: false
    exposed: false
  articles:
    enabled: false
  admin:
    enabled: true
    capability:
      index: ALL
  search:
    enabled: true
    capability:
      index: LOGIN

iconStandards:
  Camps: campground
  Directory: address-card
  Documents: file-alt
  Articles: newspaper
  Users: users

searchConfigured:
  Users: true
  Documents: true
  Sections: true
