language: php

dist: bionic

os: linux

version: ~> 1.0

addons:
  postgresql: "11"
  code_climate:
    repo_token: CodeClimateTokenForReplacement

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - postgresql
  - redis
  - elasticsearch

env:
  - DB=postgres

jobs:
  include:
    - name: "PHP 7.2"
      php: 7.2

    - name: "PHP 7.3"
      php: 7.3

    - name: "PHP 7.4"
      php: 7.4

before_install:
  - cp config/app_db.travis.php config/app_db.php
  - cp config/app_file.travis.php config/app_file.php
  - cp config/app.travis.php config/app.php
  - rm config/app_queue.php
  - cp config/app_queue.travis.php config/app_queue.php

install:
  - psql --command='create database leaders;' --username=postgres
  - composer install
  - composer validate

before_script:
  - composer run-script post-install-cmd --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - sh -c "bin/cake code_completion generate -d"
  - composer cs-check
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --id CodeClimateTokenForReplacement --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

