language: php

dist: bionic
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - redis-tools
      - redis-server

sudo: false

env:
  - DB=postgres

services:
  - postgresql
  - redis

matrix:
  fast_finish: true

  include:
    - name: "PHP 7.1"
      phpenv: 7.1

    - name: "PHP 7.2"
      phpenv: 7.2

    - name: "PHP 7.3"
      phpenv: 7.3

before_script:
  - psql -c 'create database leaders;' -U postgres
  - cp config/app_db.travis.php config/app_db.php
  - cp config/app_file.travis.php config/app_file.php
  - cp config/app.travis.php config/app.php
  - composer install
  - composer run-script post-install-cmd --no-interaction
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"
  - sh -c "bin/cake annotations all -v -d --ci"
  - sh -c "bin/cake code_completion generate -d"

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
