language: php

dist: bionic
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

sudo: false

matrix:
  fast_finish: true

  include:
    - name: "PHP 7.1"
      php: 7.1
      env:
        - PGPORT=5433
        - DB=postgres
      services:
        - postgresql
        - redis-server

    - name: "PHP 7.2"
      php: 7.2
      env:
        - PGPORT=5433
        - DB=postgres
      services:
        - postgresql
        - redis-server

    - name: "PHP 7.3"
      php: 7.3
      env:
        - PGPORT=5433
        - DB=postgres
      services:
        - postgresql
        - redis-server

before_script:
  - psql -c 'create database leaders;' -U postgres
  - cp config/app_db.travis.php config/app_db.php
  - cp config/app_file.travis.php config/app_file.php
  - cp config/app.travis.php config/app.php
  - composer install
  - composer run-script post-install-cmd --no-interaction
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"
  - sh -c "bin/cake code_completion generate -d"

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
