language: php

dist: trusty

sudo: false

env:
  - DB=postgres

services:
  - postgresql

matrix:
  fast_finish: true

  include:
    - name: "PHP 7.1"
      php: 7.1

    - name: "PHP 7.2"
      php: 7.2

before_script:
  - psql -c 'create database leaders;' -U postgres
  - cp config/app_db.travis.php config/app_db.php
  - composer install
  - composer run-script post-install-cmd --no-interaction
  - sh -c "bin/cake database build"
  - sh -c "bin/cake database seed"

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false