# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      - image: circleci/postgres:11.4-ram
        environment:
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: leaders
      
      - image: redis:latest

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo apt install postgresql-client-11  php-pgsql
      - run: echo 'export PATH=/usr/lib/postgresql/11/bin/:$PATH' >> $BASH_ENV
      - run: export COMPOSER_PROCESS_TIMEOUT=900
      - run: mv config/app_file.travis.php config/app_file.php
      - run: mv config/app.travis.php config/app.php
      - run: mv config/Environment/travis_parameters.yml config/Environment/app_parameters.yml
      - run: rm phpunit.xml.dist
      - run: mv phpunit-travis.xml.dist phpunit.xml.dist

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - run: composer validate

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # run tests with phpunit or codecept
      - run: composer cs-check
      - run: composer test
      
      - store_test_results:
          path: clover.xml
